version: "3.8"

services:
  jenkins:
    build: ../simple-django-app-taller2
    container_name: jenkins
    user: root
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ../simple-django-app-taller2:/workspace
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - devopsnet

  app:
    build: ./app
    container_name: django-app
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - jenkins
    networks:
      - devopsnet

volumes:
  jenkins-data:

networks:
  devopsnet:
    driver: bridge
